### PR TITLE
Italian translation (it)

### PR DESCRIPTION
**Pull request by atomotic**

### CODE REVIEW

**Comment by ipf** [comment]
Hi - our AI had some remarks (as no one of us can really judge the translations):

1. "Contents" should be translated to "Contenuti" (plural) instead of "Contenuto" (singular) to match the English plural form.
2. "Current Element" could be translated to "Elemento attuale" to better convey the meaning.
3. "Document" and "Documents" are correctly translated, but it's worth noting that in Italian, the plural form "Documenti" is often used for both singular and plural contexts.
4. "Exit fullscreen" could be translated to "Esci dalla modalità a tutto schermo" to better match the Italian syntax.
5. "Fulltext not available for this page" could be translated to "Il testo integrale non è disponibile per questa pagina" to better convey the meaning.
6. "Info" is a bit informal, and "Informazioni" is already used for "About TIFY". Consider translating "Info" to "Informazione" or "Dettagli" instead.
7. "Jump to page" could be translated to "Vai alla pagina numero" to better match the Italian syntax.
8. "Logical page" is a technical term, and the translation "Pagina logica" might not be immediately clear to all users. Consider adding a tooltip or explanation to clarify the meaning.
9. "Pan" is a bit ambiguous, and "Panorama" might not be the best translation. Consider translating it to "Scorri" or "Sposta" to better convey the action of panning an image.
10. "Physical page" could be translated to "Pagina fisica reale" to better distinguish it from "Logical page".
11. "Related Resources" could be translated to "Risorse correlate" or "Risorse associate" to better convey the meaning.
12. "Renderings" is a technical term, and the translation "Rendering" might not be immediately clear to all users. Consider adding a tooltip or explanation to clarify the meaning.
13. "Saturation" is a technical term, and the translation "Saturazione" is correct, but it might not be immediately clear to all users. Consider adding a tooltip or explanation to clarify the meaning.
14. "Toggle double-page" could be translated to "Attiva/disattiva visualizzazione doppia pagina" to better match the Italian syntax.
15. "Toggle image filters" could be translated to "Attiva/disattiva filtri per immagini" to better match the Italian syntax.

Do these suggestions make sense?

**Comment by atomotic** [comment]
`1` `6` `9` are absolutely correct suggestion, my translation was approximate.
The other suggestions doesn't improve much, but they are ok to be used.

**Comment by t11r** [comment]
Since “contents” is short for “table of contents”, maybe it should be translated as “indice”?

**Comment by atomotic** [comment]
Sure, "indice" is correct. I hadn't used it in my translation because it's a term mainly associated with books, whereas an IIIF manifest could contain etherogenous things. But this is a philosophical matter, "indice" could work if you prefer.

**Comment by t11r** [comment]
See https://github.com/tify-iiif-viewer/tify/pull/172

**Pull request closed without merging**
