### PR TITLE
Add Croatian translation (hr)

### PR DESCRIPTION
**Pull request by hrvoj3e**

### CODE REVIEW

**Comment by t11r** [comment]
Thanks a lot, @hrvoj3e!

@ipf and @paulpestov, you know anyone who speaks Croation and could verify the translation?

**Comment by ipf** [comment]
Our AI has some suggestions - do they make sense?

1. "$info" should be translated to "Informacije" instead of "Info" to match the Croatian syntax.
2. "(Invalid value)" could be translated to "Nevaljana vrijednost" to better convey the meaning.
3. "About TIFY" could be translated to "O TIFY-ju" to better match the Croatian syntax.
4. "Brightness:" should be translated to "Svjetlina:" to match the Croatian syntax.
5. "Close PDF list" could be translated to "Zatvori popis PDF-a" to better match the Croatian syntax.
6. "Collapse all" and "Expand all" could be translated to "Smanji sve" and "Proširi sve" respectively to better match the Croatian syntax.
7. "Contributors" could be translated to "Suradnici" to better match the Croatian syntax.
8. "Current Element" could be translated to "Trenutni element" to better match the Croatian syntax.
9. "Dismiss" could be translated to "Odbaci" to better match the Croatian syntax.
10. "Filter collection" and "Filter pages" could be translated to "Filtriraj kolekciju" and "Filtriraj stranice" respectively to better match the Croatian syntax.
11. "Fulltext not available for this page" could be translated to "Cijeli tekst nije dostupan za ovu stranicu" to better convey the meaning.
12. "Image filters" could be translated to "Filtri slika" to better match the Croatian syntax.
13. "Jump to page" could be translated to "Skoči na stranicu" to better match the Croatian syntax.
14. "License" could be translated to "Licenca" to better match the Croatian syntax.
15. "Literature Management" could be translated to "Upravljanje literaturom" to better match the Croatian syntax.
16. "Logical page" could be translated to "Logička stranica" to better match the Croatian syntax.
17. "Metadata" could be translated to "Metapodaci" to better match the Croatian syntax.
18. "Next section" and "Previous section" could be translated to "Sljedeća sekciona" and "Prethodna sekciona" respectively to better match the Croatian syntax.
19. "Other Formats" could be translated to "Ostali formati" to better match the Croatian syntax.
20. "Pan" could be translated to "Panorama" to better match the Croatian syntax.
21. "PDFs for each element" could be translated to "PDF za svaki element" to better match the Croatian syntax.
22. "Physical page" could be translated to "Fizička stranica" to better match the Croatian syntax.
23. "Provided by" could be translated to " Pruža" to better match the Croatian syntax.
24. "Related Resources" could be translated to "Povezani resursi" to better match the Croatian syntax.
25. "Renderings" could be translated to "Renderiranja" to better match the Croatian syntax.
26. "Report a bug" could be translated to "Prijavi grešku" to better match the Croatian syntax.
27. "Saturation" could be translated to "Zasićenje" to better match the Croatian syntax.
28. "Source" could be translated to "Izvor" to better match the Croatian syntax.
29. "Summary" could be translated to "Sažetak" to better match the Croatian syntax.
30. "Toggle double-page" could be translated to "Dvije stranice na stranici" to better match the Croatian syntax.
31. "Toggle image filters" could be translated to "Filtri slika" to better match the Croatian syntax.
32. "User guide" could be translated to "Korisnički vodič" to better match the Croatian syntax.
33. "Version" could be translated to "Verzija" to better match the Croatian syntax.

**Comment by t11r** [comment]
@hrvoj3e, could you please have a quick look at this? I’ve got a feeling that the AI suggestions may be nonsensical, but none of us speaks any Croation.

**Comment by hrvoj3e** [comment]
I have reviewed it and corrected.
AI had some good suggestions.

**Comment by t11r** [comment]
Great, thanks!

**Pull request merged**
