### PR TITLE
Next

### PR DESCRIPTION
**Pull request by t11r**
Ready to merge.

### CODE REVIEW

**Comment by ipf** [comment]
Not sure if I get it right, but according to https://iiif.io/api/presentation/2.1/#linked-data-context-and-extensions the context provided in your example is not correct
>  As the top level resource must have the IIIF Presentation API context,

**Comment by t11r** [comment]
The question is: Should TIFY refuse to display an otherwise valid document just because the `@context` string is invalid? It works in every other viewer.

**Comment by ipf** [comment]
Well, hard to decide. I cannot check the document, as it seems to have multiple [issues](https://iiif.io/api/presentation/validator/service/validate?format=json&version=2.0&url=https://bluemountain.princeton.edu/exist/restxq/iiif/bmtnaae_1918-12_01/manifest) or the validator is broken.
The main task of a viewer is not validation - we could add this manifest to the test set, but cui bono?
If you find any mechanism besides checking if `@context` is existing, go ahead. Otherwise I'd suggest to not load the document.
What about adding a link to the vaidator with the invalid manifest to the error message?

**Comment by t11r** [comment]
It should not matter to us if the manifest is valid. If it contains data that TIFY can parse, it should be displayed. Maybe log a warning to the console.

**Pull request merged**
